### ISSUE TITLE
Cannot create directory error

### ISSUE THREAD

**Issue by darknailblue** [afragen/github-updater#248]
I'm having trouble updating a theme while doing local development.  The error I'm seeing is:

Could not create directory. darknailblue-anfoundation-9e4a73ca286acbad059914202b03401f0b4b8a65/library/vendors/acf-font-awesome/better-font-awesome-library/lib/fallback-font-awesome

What could be causing this?  Is the string too long?

**Comment by afragen** [comment]
Was this a symlink directory in the local environment? That's where I've seen this issue when the main local folder is deleted, accidentally in most cases. 

What branch are you working with?

**Comment by afragen** [comment]
What's the URI for the theme?

**Comment by darknailblue** [comment]
Working with the current master branch.

This is not a Symlink but the local files reside on another hard drive separate from the XAAMP server (if that makes any difference)

**Comment by darknailblue** [comment]
This is all happening locally now from a private github repo.  No working URI

**Comment by afragen** [comment]
Can you check to see if the external drive is mounted and that the files are present? Also, the initial directory naming is likely to cause an issue with theme updating.

You can use the remote install feature of the plugin to install and correctly rename the directory.

**Comment by darknailblue** [comment]
Its not an external drive.  Its in the computer.  Its definitely mounted as I have 150+ dev sites currently on it that all work.

**Comment by darknailblue** [comment]
Just tried the install theme option and no luck.  Same errors.

**Comment by afragen** [comment]
Has this ever worked for you in your current setup? It might be that your local setup is preventing this from working. 

Are the permissions of the containing wp-content/themes folder writable by your web server?

**Comment by darknailblue** [comment]
The are definitely writable as I have "uploaded" plugins locally with no
issue.  I'm deploying to a live server now and will test again.




All the best,

---------------------------------------------------------------------------------------------
*Christopher Carvache*
New Leaf Web Solutions
http://newleafwebsolutions.com
Office: 860.906.7802  ::  Fax: 888.760.5945
[image: Like us on Facebook] Like us on Facebook
<http://www.facebook.com/newleafwebsolutions>  [image: Follow us on
Twitter] Follow
us on Twitter <https://twitter.com/NLWebSolutions>
Interested in a free one hour consultation?  Schedule one today!
<http://newleafwebsolutions.com/free-consultation/>

**Comment by afragen** [comment]
Please let me know, thanks.

**Comment by darknailblue** [comment]
This worked perfect on the live site.  I'm wondering now... my local development environment is on a Windows machine.  I've had many problems using CL based web dev tools (big surprise eh?) but the more specific one I've encountered was setting up SASS / SCSS in that Windows required some weird kind of SSH authentication.

I'm wondering if this might have something to do with that?

**Comment by afragen** [comment]
I have no idea, but as the issue is resolved on he live site I'll close this issue. Thanks.

**Comment by darknailblue** [comment]
:(

Still an issue man, especially when using the plugin as part of a production workflow.  Is there some way I can turn any level of debugging on for this especially when this is creating directories so I can drill down a bit?  If there is an error being triggered, there has to be SOME way of getting more information on it.  Right?

**Comment by afragen** [comment]
Do you mean the error is occurring both locally and remotely?

**Comment by darknailblue** [comment]
Just locally.  By "production workflow" I just meant the process of developing locally and the pushing changes to either a staging or production server.  Sorry I was unclear.

**Comment by afragen** [comment]
I don't really know if there's any additional level of debugging that can be done as it's all WordPress core that's making directories.

Do you have `define( 'FS_METHOD', 'direct' );` in your wp-config.php? It might help. Sorry, I don't really have any other ideas. I'm not on Windows so I can't duplicate your setup.

**Comment by darknailblue** [comment]
Yes this is set to be true as well.  No luck.  Here's just another reason why I'm considering getting a Mac :)

**Comment by afragen** [comment]
FYI, I've seen this error locally when I've accidentally updated a plugin/theme that was a symlink. Unfortunately what happened was my Git repo was deleted and the symlink remained.
