### ISSUE TITLE
Bitbucket private repo Update error 

### ISSUE THREAD

**Issue by yeomann** [afragen/github-updater#482]
So, i have to confirm this, from [#474](https://github.com/afragen/github-updater/issues/474) if you see my last message there, [referenced comment](https://github.com/afragen/github-updater/issues/474#issuecomment-256845301)
 I did some digging and experiment. I have created new account on bitbucket and pushed my repo there and let it be Public. After filling bit bucket settings in github updater setting page, i saw notification of new update for my plugin and was able to update successfully my bitbucket hosted plugin with github-updater6.0.0. New version i.e 6.0.2 failed miserably [#481](https://github.com/afragen/github-updater/issues/481)
Now, after making the same Repo private i recived the same error mentioned in issue 474 and same error message as shown below in picture. 
![errorupdate](https://cloud.githubusercontent.com/assets/5970751/19796840/c3698d9e-9cef-11e6-9175-d647a5884620.jpg)

I now strongly believe my username and password in bitbucket settings of github-updater are correct and In case repo is private, github-updater is having trouble with bitbucket api. Please help.

Many thanks.

**Comment by afragen** [comment]
Can you update from the update-core.php page?

**Comment by yeomann** [comment]
unfortunately, i tried and couldn't. This was the output i end up with 

```
The update process is starting. This process may take a while on some hosts, so please be patient.

Enabling Maintenance mode…

Updating Plugin visual composer adon (1/1)
Downloading update from https://bitbucket.org/danish_innovia/innovia-vcextend/get/master.zip…
Unpacking the update…
An error occurred while updating visual composer adon: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
Disabling Maintenance mode…

Some of your translations need updating. Sit tight for a few more seconds while we update them as well.

Updating translations for WP Job Manager (tr_TR)…

Translation updated successfully.

Updating translations for Twenty Fifteen (tr_TR)…

Translation updated successfully.

Updating translations for Twenty Fourteen (tr_TR)…

Translation updated successfully.

Updating translations for Twenty Sixteen (tr_TR)…

Translation updated successfully.

All updates have been completed.

Return to Plugins page | Return to WordPress Updates page
```

**Comment by afragen** [comment]
I think I found the problem. I switched to loading the Bitbucket authentication headers in the `class Bitbucket_API` class from `class Base`. Moving them back seems to have fixed the issue here.

Update to 6.0.0.3 and let me know please.

**Comment by yeomann** [comment]
Weird, I can't see any notification of update for GitHub-updater plugin?! How I should upgrade to 6.0.0.3 also under your repo release, I can see only 6.0.0 version.

**Comment by afragen** [comment]
Switch to branch `develop`

**Comment by yeomann** [comment]
Can't see switch options how else can i do?
![notshowingbranches](https://cloud.githubusercontent.com/assets/5970751/19817715/761766a4-9d55-11e6-869a-4d3971a8c76f.png)

**Comment by afragen** [comment]
My guess is the folder is misnamed.

**Comment by yeomann** [comment]
You might have read last comment of mine from #481. So, after unzipping new downloaded repo, i got github-updater-develop as name. Which didn't show me switch branch option. Even after renaming to github-updater, It was the same story. Unfortunately, About updating from bitbucket private repo, it didn't do the job from plugin panel but update worked from only update-core panel with disabling my plugin.

**Comment by afragen** [comment]
Just so we have a new starting point. You have GHU v6.0.0.4 (develop) installed and running.

In my test installation, I renamed my folder to `github-updater-develop`. I re activated the plugin and was able to see branch switching. I was also able to update my Bitbucket private test plugin from the plugins page.

What error are you getting when you attempt to update from the plugins page. Opening up your browser console error log should show you the errors.

**Comment by cbratschi** [comment]
+1: I have the same issue after upgrading to the 4.x version.

**Comment by afragen** [comment]
I cannot replicate this issue. Is it possible to give `afragen` `read` access to these repos?

**Comment by cbratschi** [comment]
@afragen I applied your patch but this did not change anything. Unfortunately I cannot give you access to our BitBucket account. But if you need any logs let me know.

Is there a simple way to downgrade? I already upgraded our staging and production environments.

**Comment by afragen** [comment]
@cbratschi I don't need access to the whole account. I would just need `read` access to the repository in question so I can see if there's an issue.

Can you share the files headers?

**Comment by yaronguez** [comment]
I'm having the same issue and can grant you access if you'd like to debug.

**Comment by afragen** [comment]
Yes please.

**Comment by yeomann** [comment]
@afragen @yaronguez  I grant you guys Read access.
also @afragen i gave you access on my wp site as well.

**Comment by yeomann** [comment]
okay another update, i have installed new WordPress, downloaded and installed new GHU v6.0.0.4 (develop). This time didn't enable naming extend thing and clicked on enable branch switch and wrote my bit-bucket credentials. Lastly, clicked on private repo checkbox.  Now after some refreshes, Switching branch option is being shown now. which is great :smile_cat: 
To test again that private repo update will work, i pused a test commit. Alas, I couldn't update and received same death message i.e 
`Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
`

**Comment by afragen** [comment]
@yeomann I found a bug, thanks. Update to 6.0.0.5 and let me know if you get the same error.

**Comment by afragen** [comment]
@yeomann I was able to remote install, revert version, and update successfully from plugin page, using v6.0.0.5

**Comment by yaronguez** [comment]
@afragen I tried to manually install 6.0.0.5 and got the error:
` Fatal error: Cannot use object of type stdClass as array in /nas/content/live/gcwaralpha/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 1050`

I deactivated it and tried activating the clear-github-updater-cache.php file and then reactivated it and still get the error. The only version I can successfully activate is 6.0.0 which throws the zip error when I try to update a plugin.

**Comment by afragen** [comment]
Can you install and activate the Flush cache plugin?

**Comment by afragen** [comment]
https://github.com/afragen/clear-github-updater-cache

**Comment by yaronguez** [comment]
Yes, I tried that. I had to deactivate github-updater to access the site at all since everything was white screen. Then I installed and activated the flush cache plugin. Then I deactivated the flush cache plugin and tried installing 6.0.5 again and again got the white screen.

**Comment by afragen** [comment]
The error is because the cache isn't clear. Install but don't activate 6.0.0.5, activate the clear cache plugin, then activate GHU

**Comment by afragen** [comment]
Do you have any caching enabled on your site?

**Comment by yaronguez** [comment]
Yes, it's WP Engine and they have their own cache. What stage should I try to clear it?

**Comment by yaronguez** [comment]
Okay, installing but not activating github-updater, installing and activating clear cache plugin, activating github-updater and clearing WP Engine cache seems to have fixed the problem. It also seems that I have to now clear WPEngine cache in order for plugin updates from BitBucket to be recognized. Is that expected? Thanks for all your help!

**Comment by afragen** [comment]
I can't speak to how WP Engine's caching works but I would bet that it clears and refreshes more frequently than GHU's cache. I realize it's difficult to be patient but once you've satisfied yourself that everything works, give yourself 12 hours and see if the update shows.

**Comment by yeomann** [comment]
great work @afragen i'll check and tried to update shortly. Looking for returning with good news! Cheers.

**Comment by yeomann** [comment]
i was not able to update same error with v6.0.5 i think i will delete everything clear cache and start over to see, If i'll be able to update successfully (hopefully yes) or not.

**Comment by afragen** [comment]
And...

**Comment by cbratschi** [comment]
If I switch to the developer branch the updater tells me I am already at the latest version.

**Comment by afragen** [comment]
It does that sometimes. Keep trying until it works. Shouldn't take too many tries.

**Comment by cbratschi** [comment]
@afragen Still the same message after ten tries. It does not matter which branch I'm selecting.

**Comment by afragen** [comment]
@cbratschi keep trying. It's the one thing I could never figure out how to override.

**Comment by afragen** [comment]
@yeomann sorry for others hijacking the issue. Are you still having problems.

**Comment by afragen** [comment]
@cbratschi I think I've fixed the _already up to date_ issue https://github.com/afragen/github-updater/commit/4dd351fad3c847eb3e1a9afe8549edc4efb36303

**Comment by cbratschi** [comment]
@afragen Tried now many times but I was still not able to switch to the development version. When will you push the update to production?

**Comment by afragen** [comment]
I should be pushing this out in next couple of days. Have you recently tried to switch?

**Comment by afragen** [comment]
Another way to force a switch would be to edit the main file and set `GitHub Branch: master` to `GitHub Branch: develop`. Since the `master` branch will always be _behind_ the `develop` branch version-wise, an update will display once the cache/transients is/are refreshed.

**Comment by cbratschi** [comment]
@afragen I've reset the cache and after that it was working. I could successfully update my theme after installing the development version. Thanks a lot.

**Comment by afragen** [comment]
@yeomann are you still having this issue or should we close?

**Comment by deckerweb** [comment]
I am sorry, but I have the same issue now with Bitbucket after using Bitbucket for a side project with a private repo.

**Comment by afragen** [comment]
@deckerweb I was able to install and update your plugin too. 👍 
You should take a look at https://github.com/afragen/wp-dependency-installer
