### ISSUE TITLE
PHP Notices at plugins and themes page

### ISSUE THREAD

**Issue by calvintam236** [afragen/github-updater#508]
```
Notice: Undefined property: stdClass::$remote_version in /home/xxxx/public_html/staging/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 815

Notice: Undefined property: stdClass::$requires_wp_version in /home/xxxx/public_html/staging/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 816

Notice: Undefined property: stdClass::$requires_php_version in /home/xxxx/public_html/staging/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 817

Notice: Undefined property: stdClass::$remote_version in /home/xxxx/public_html/staging/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 815

Notice: Undefined property: stdClass::$requires_wp_version in /home/xxxx/public_html/staging/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 816

Notice: Undefined property: stdClass::$requires_php_version in /home/xxxx/public_html/staging/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php on line 817
```

I notice that these notices repeatedly showing up at both plugin and theme list pages after updating to 6.1.0. Current version 6.1.1 on Multisite.

**Comment by afragen** [comment]
Are you using any caching?

**Comment by calvintam236** [comment]
You mean caching plugin? I have installed Autoptimize, and I don't think it is running in admin UI.

**Comment by afragen** [comment]
Is your server using any caching? Are these notices continuing?

**Comment by calvintam236** [comment]
No. I run the updater plugin at staging server with HTTP Auth and not with any server-end caching except Autoptimize the WordPress plugin.

**Comment by afragen** [comment]
Do you still see these notices?

**Comment by calvintam236** [comment]
Yes, and they seem to appear at blogs only plugin & theme page (not inside network admin).

**Comment by afragen** [comment]
Thanks for that last bit of info. I can reproduce it now.

**Comment by afragen** [comment]
Thanks for the report. Should now be fixed with https://github.com/afragen/github-updater/commit/4b55847fafc18de5d3da8e2377f6142b16b7215d

**Comment by ihorvorotnov** [comment]
I'm using latest release 6.1.1 with WordPress 4.7 multisite, and still see these notices. It's local Vagrant install, no caching.

<img width="1398" alt="screen shot 2016-12-30 at 17 46 25" src="https://cloud.githubusercontent.com/assets/1066083/21567901/92d433aa-ceb8-11e6-85e9-44cae2fd1161.png">

**Comment by afragen** [comment]
@ihorvorotnov are these errors present if you switch to the `develop` branch? Not sure it has been released and tagged to `master` yet.
